### ISSUE TITLE
Opening a FStar file raises an exception

### ISSUE THREAD

**Issue by anithag** [FStarLang/VimFStar#15]
Error detected while processing /Users/anithagollamudi/.vim/bundle/VimFStar/ftplugin/fstar.vim:
line   47:
On my Macbook, opening any FStar using 'vim' gives this error.

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/anithagollamudi/.vim/bundle/VimFStar/ftplugin/fstar-inter.py", line 62, in fstar_init
    fst=Popen([fstarpath,'--in'],stdin=PIPE, stdout=PIPE,bufsize=1,close_fds=ON_POSIX)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
```
OSError: [Errno 8] Exec format error

**Comment by msprotz** [comment]
Yeah I use vim but I don't use this plugin. As far as I know, I never could get it to work reliably...

**Comment by catalin-hritcu** [comment]
@ngrimm Any interest in reviving the vim plugin?
